### ISSUE TITLE
Using framework

### ISSUE THREAD

**Issue by limelect** [aehimself/vStarCamDownloader#1]
I am using D10.2.3 to compile
      input.Write([$78, $DA], 2);      <<<<<<<write cannot be called with such arguments
   json := TJSONObject(TJSONObject.ParseJSONValue(tb, 0, [TJSONObject.TJSONParseOption.IsUTF8, TJSONObject.TJSONParseOption.RaiseExc]));  <<<< no such RaiseExc
You are using newer Delphi ? May be use also D10.2?
May be more errors?

**Comment by aehimself** [comment]
Most of the code was written in D10.2 but chunks were added on the latest, 10.4 for a while, now D11.2.

The TJSONParseOption can be solved if you leave RaiseExc out and raise an exception manually if json is not assigned. I'll have to see what overloads TBytesStream has to be able to correct it.

The earliest one I can go back is 10.4, but there might be parts which have to be re-written; yes.
Let me see what I can do.

**Comment by aehimself** [comment]
@limelect Please check and confirm, after a quick and dirty fix framework should compile now in Delphi 10.2 too.

**Comment by limelect** [comment]
Ok now it compiles
